import type { Metadata } from "next";
import "./globals.scss";
import Header from "./components/header";
import Footer from "./components/footer";
import "../styles/header.scss";
import "../styles/about.scss";
import "../styles/renew.scss";
import "../styles/producs.scss";
import "../styles/claims.scss";
import "../styles/support.scss";
import '../styles/insurance.scss';
import '../styles/faq.scss';
import '../styles/vichicleInsurence.scss';
import { ToastContainer } from "react-toastify";

export const metadata: Metadata = {
  title: "Commercial Vehicle Insurance",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <Footer />
        <ToastContainer />
      </body>
    </html>
  );
}
